# Generated by Django 3.1.6 on 2021-03-18 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelrelation', '0005_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 15, 56, 11, 482789, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='information',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 15, 56, 11, 482814, tzinfo=utc)),
        ),
    ]
