# Generated by Django 3.1.6 on 2021-03-18 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelrelation', '0006_auto_20210318_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='information',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
