# Generated by Django 3.1.6 on 2021-03-19 13:37

from django.db import migrations, models
import modelextra.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelextra', '0002_auto_20210319_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='age',
            field=models.IntegerField(validators=[modelextra.models.validate_my_age]),
        ),
    ]
